// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runMonteCarlo_
double runMonteCarlo_(double Expiry, double Strike, double Spot, double Vol, double r, unsigned long NumberOfPaths, double barrier);
RcppExport SEXP _optionPricer_runMonteCarlo_(SEXP ExpirySEXP, SEXP StrikeSEXP, SEXP SpotSEXP, SEXP VolSEXP, SEXP rSEXP, SEXP NumberOfPathsSEXP, SEXP barrierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Expiry(ExpirySEXP);
    Rcpp::traits::input_parameter< double >::type Strike(StrikeSEXP);
    Rcpp::traits::input_parameter< double >::type Spot(SpotSEXP);
    Rcpp::traits::input_parameter< double >::type Vol(VolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type NumberOfPaths(NumberOfPathsSEXP);
    Rcpp::traits::input_parameter< double >::type barrier(barrierSEXP);
    rcpp_result_gen = Rcpp::wrap(runMonteCarlo_(Expiry, Strike, Spot, Vol, r, NumberOfPaths, barrier));
    return rcpp_result_gen;
END_RCPP
}
// getMonteCarloTrend_
std::vector<double> getMonteCarloTrend_(double Expiry, double Strike, double Spot, double Vol, double r, unsigned long NumberOfPaths, double barrier);
RcppExport SEXP _optionPricer_getMonteCarloTrend_(SEXP ExpirySEXP, SEXP StrikeSEXP, SEXP SpotSEXP, SEXP VolSEXP, SEXP rSEXP, SEXP NumberOfPathsSEXP, SEXP barrierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Expiry(ExpirySEXP);
    Rcpp::traits::input_parameter< double >::type Strike(StrikeSEXP);
    Rcpp::traits::input_parameter< double >::type Spot(SpotSEXP);
    Rcpp::traits::input_parameter< double >::type Vol(VolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type NumberOfPaths(NumberOfPathsSEXP);
    Rcpp::traits::input_parameter< double >::type barrier(barrierSEXP);
    rcpp_result_gen = Rcpp::wrap(getMonteCarloTrend_(Expiry, Strike, Spot, Vol, r, NumberOfPaths, barrier));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optionPricer_runMonteCarlo_", (DL_FUNC) &_optionPricer_runMonteCarlo_, 7},
    {"_optionPricer_getMonteCarloTrend_", (DL_FUNC) &_optionPricer_getMonteCarloTrend_, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_optionPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
