# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPutOptionPrice <- function(Expiry = 0.5, Strike = 100, Spot = 105, Vol = 0.22, r = 0.05, NumberOfPaths = 10000L, barrier = 150) {
    .Call(`_putOptionPricer_getPutOptionPrice`, Expiry, Strike, Spot, Vol, r, NumberOfPaths, barrier)
}

getPutOptionPath <- function(Expiry = 0.5, Strike = 100, Spot = 105, Vol = 0.22, r = 0.05, NumberOfPaths = 10000L) {
    .Call(`_putOptionPricer_getPutOptionPath`, Expiry, Strike, Spot, Vol, r, NumberOfPaths)
}

rcpp_hello <- function() {
    .Call(`_putOptionPricer_rcpp_hello`)
}

