# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runMonteCarlo <- function(Expiry = 0.5, Strike = 100, Spot = 105, Vol = 0.22, r = 0.05, NumberOfPaths = 10000L, barrier = 150) {
    .Call(`_optionPricer_runMonteCarlo`, Expiry, Strike, Spot, Vol, r, NumberOfPaths, barrier)
}

getMonteCarloTrend <- function(Expiry = 0.5, Strike = 100, Spot = 105, Vol = 0.22, r = 0.05, NumberOfPaths = 10000L, barrier = 150) {
    .Call(`_optionPricer_getMonteCarloTrend`, Expiry, Strike, Spot, Vol, r, NumberOfPaths, barrier)
}

